name: weather
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  weather_icons: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  geolocator_apple: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/Image.png
    - assets/images/House2.png


flutter_icons:
  android: true
  image_path: "assets/icons/weatherApp_icon.png"

  uses-material-design: true





